site_name: Muran's Notes
site_url: http://note.muransama.top/
repo_name: T-muran/Note
repo_url: https://github.com/T-muran/Note
edit_uri: blob/main/docs/

copyright: >
  Copyright &copy; 2022-2024 T-muran. All rights reserved.<br>
  Contents are licensed under the <u><a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC-BY-NC-SA 4.0</a></u> license, except when otherwise noted.


theme: 
  name: material
  language: zh
  favicon: &site-icon assets/images/favicon.png
  custom_dir: overrides

  icon:
    repo: fontawesome/brands/github
    logo: octicons/log-24
    tag:
      default: fontawesome/solid/hashtag

  font:
    text: LXGW WenKai Screen
    code: JetBrains Mono

  features:
    - announce.dismiss

    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - content.action.edit 

    - navigation.top
    - navigation.path
    - navigation.footer

    - toc.follow

    - search.suggest
    - search.highlight
    - search.share

  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/circle-slice-4
      name: Auto Mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    toggle:
      icon: material/circle-slice-8
      name: Light Mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/circle-outline
      name: Dark Mode

markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format      

extra:
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/T-muran
    - name: Mail
      icon: fontawesome/solid/envelope
      link: mailto:tangmuransama@gmail.com

  tags: { "": default }

plugins:
  - glightbox:
      auto_caption: true
  - search:
      lang: 
        - en
        - zh
  - git-revision-date-localized:
      type: timeago
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - blog/** 
        - news/** 
  - git-committers:
      # enabled: !ENV [CI, false]
      repository: T-muran/Note
      branch: main
      exclude:
        - blog/** 
        - news/** 
  - blog:
      enabled: true
      blog_toc: false 
      archive: true
      archive_toc: false 
      archive_date_format: yyyy 年 MM 月
      archive_url_date_format: yyyy/MM
      categories: true
      categories_toc: false
      post_date_format: yyyy-MM-dd
      post_readtime: true
      post_readtime_words_per_minute: 180
      post_url_format: "posts/{file}-{date}"
      post_url_date_format: yyyy-MM-dd
      post_excerpt: required
      post_excerpt_max_authors: 0
      authors: true
      pagination: true
      pagination_per_page: 10
      pagination_format: "~2~"
      pagination_if_single_page: true
      pagination_keep_content: false
  - rss:
      match_path: blog/posts/.* 
      comments_path: "#__comments"
      date_from_meta:
          as_creation: date
          default_timezone: Asia/Shanghai
      categories:
        - categories
      image: *site-icon

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/fonts/LXGW WenKai Screen/font.css
  - assets/fonts/JetBrains Mono/font.css
  - assets/stylesheets/theme.css
  - assets/stylesheets/feature.css


nav:
  - index.md
  - 网站资源: websiteRes.md
  - 数学: 
    - 高等数学: 
      - 极限与连续: Math/Advanced-Mathematics/Limit-Continuous.md
      # - 微分学: 
      - 积分学: 
        - 高斯积分: Math/Integral-Calculus/Gaussian-Integral.md
        - 拉格朗日乘子法: Math/Integral-Calculus/Lagrange-Multipliers.md
  - 计算机:
    - 编程语言: 
      - C/C++: 
        - STL 相关: 
          - STL基础: CS/Language/C-CPP/STL/STL-base.md
      - C#: 
        - 代码规范: CS/Language/CSharp/Coding-Convention.md  
    - 数据结构与算法: 
      - 学习资料: CS/Algorithms/res.md
      - 搜索:
        - DFS-搜索: CS/Algorithms/Search/DFS-Search.md
      - 动态规划:
        - 记忆化搜索: CS/Algorithms/Dynamic-Programming/Memorization-Search.md
      - 数据结构: 
        - 并查集: CS/Algorithms/Data-Structure/Union-Find.md
      - 图论: 
        - 最短路径: CS/Algorithms/Graph-Theory/Shortest-Path.md
    - 计算机图形学:
      - OpenGL: 
        - 深度测试: CS/Cg/OpenGL/Depth-Testing.md
        - 模板测试: CS/Cg/OpenGL/Stencil-Testing.md 
        - 混合: CS/Cg/OpenGL/Blending.md
    - 设计模式:
      - 简介: CS/Design-Patterns/Introduction.md
      - 创建型模式: CS/Design-Patterns/Creational.md
      - 结构型模式: CS/Design-Patterns/Structural.md
      - 行为型模式: CS/Design-Patterns/Behavioral.md