site_name: Muran's Notes
site_url: http://note.muransama.top/
repo_name: T-muran/Note
repo_url: https://github.com/T-muran/Note
edit_uri: blob/main/docs/

copyright: >
  Copyright &copy; 2022-2024 T-muran. All rights reserved.<br>
  Contents are licensed under the <u><a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC-BY-NC-SA 4.0</a></u> license, except when otherwise noted.


theme: 
  name: material
  language: zh
  favicon: &site-icon assets/images/favicon.png
  custom_dir: overrides

  icon:
    repo: fontawesome/brands/github
    logo: octicons/log-24
    tag:
      default: fontawesome/solid/hashtag

  font:
    text: LXGW WenKai Screen
    code: JetBrains Mono

  features:
    - announce.dismiss

    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - content.action.edit 

    - navigation.top
    - navigation.path
    - navigation.footer

    - toc.follow

    - search.suggest
    - search.highlight
    - search.share

  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/circle-slice-4
      name: Auto Mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    toggle:
      icon: material/circle-slice-8
      name: Light Mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/circle-outline
      name: Dark Mode

markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format      

extra:
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/T-muran
    - name: Mail
      icon: fontawesome/solid/envelope
      link: mailto:tangmuransama@gmail.com

  tags: { "": default }

plugins:
  - glightbox:
      auto_caption: true
  - search:
      lang: 
        - en
        - zh
  - git-revision-date-localized:
      type: timeago
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - blog/** 
        - news/** 
  - git-committers:
      # enabled: !ENV [CI, false]
      repository: T-muran/Note
      branch: main
      exclude:
        - blog/** 
        - news/** 
  - blog:
      enabled: false

  - rss:
      match_path: blog/posts/.* 
      comments_path: "#__comments"
      date_from_meta:
          as_creation: date
          default_timezone: Asia/Shanghai
      categories:
        - categories
      image: *site-icon

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/fonts/LXGW WenKai Screen/font.css
  - assets/fonts/JetBrains Mono/font.css
  - assets/stylesheets/theme.css
  - assets/stylesheets/feature.css

hooks:
  - scripts/path.py
